apiVersion: v1
kind: ServiceAccount
metadata:
  name: defender-updater-sa
  namespace: twistlock
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: defender-udpater-clusterrole
rules:
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: defender-udpater-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: defender-udpater-sa
    namespace: twistlock
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
