apiVersion: batch/v1
kind: CronJob
metadata:
  name: defender-updater
  namespace: twistlock
spec:
  schedule: "0 18 * * *" # Runs daily at 6:00 PM UTC
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: defender-updater-sa
          containers:
            - name: updater
              image: bsantacruz/alpine-kubectl:2.1
              volumeMounts:
                - name: script
                  mountPath: /scripts
                  readOnly: false
              env:
                - name: AK
                  valueFrom:
                    secretKeyRef:
                      name: prisma-secrets
                      key: AK
                - name: SK
                  valueFrom:
                    secretKeyRef:
                      name: prisma-secrets
                      key: SK
              command: ["/bin/sh", "/scripts/DefenderUpdater.sh"]
          volumes:
            - name: script
              configMap:
                name: defender-updater-script-configmap
          restartPolicy: OnFailure
