apiVersion: v1
kind: ServiceAccount
metadata:
  name: defender-updater-sa
  namespace: twistlock
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: defender-updater-role
rules:
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: defender-updater-rolebinding
subjects:
  - kind: ServiceAccount
    name: defender-updater-sa
    namespace: twistlock
roleRef:
  kind: Role
  name: defender-updater-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: prisma-secrets
  namespace: twistlock
type: Opaque
data:
  AK: YourAccessKey-Base64encode
  SK: YourSecretKey-Base64encode
